name: noro-main

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.13
  - biopython
  - pandas
  - pyyaml
  - numpy
  - matplotlib
  - seaborn
  - tabulate
  - openpyxl
  - requests
  - jupyterlab
  - seqkit
  - varvamp
  - mafft
  - ncbi-datasets-cli
  - entrez-direct
  - cd-hit
  - vsearch
  - fasttree
  - iqtree
  - blast
  - pip
  - pip:
      - assay_blast
