
paths: 
  ## input files:
  input_fasta: data/01_curated/fasta/filtered.fna
  input_dir: data/03_primer_evaluation/novel/varvamp_outputs
  
  ## output files:
  extracted_fasta: data/03_primer_evaluation/filtered_candidates.fasta
  output_fasta_dir: data/03_primer_evaluation/novel/fasta

  ## temp files:
  temporary_web_crawler_dir: data/03_primer_evaluation/novel/temporary_web_crawler_data
