
paths: 
  ## input files:
  input_fasta: data/01_curated/output/final_complete.fna
  small_input_fasta: data/02_alignments/msa_inputs/final_global.fasta
  input_dir: data/03_primer_evaluation/novel/varvamp_outputs/select_primers.tsv
  
  ## output files:
  extracted_fasta: data/03_primer_evaluation/filtered_candidates.fasta
  output_fasta_dir: data/03_primer_evaluation/novel/fasta

  ## temp files:
  web_crawler_dir: data/03_primer_evaluation/novel/fasta/web_crawler_data
