taxon: norovirus

paths:
  download_dir: data/00_raw/ncbi_datasets/downloads
  download_zip: data/00_raw/ncbi_datasets/downloads/norovirus.zip
  extracted_dir: data/00_raw/ncbi_datasets/extracted

download:
  host: human
  complete_only: false

  include:
    annotation: true
    protein: false
    biosample: false
    cds: true
